### PR TITLE
Fixes #36

### LINKED ISSUE #36: Nees updating to support videojs 5.0
Hi this needs updating to support videojs 5.0.

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by paladox** [comment]
@TheDJ do I have permission to upload this patch.

**Comment by RomanEmelyanov** [comment]
@paladox Hi! Can not confirm that your patch works with 5.0 -> http://us2.ytapi.com/dev/50.php
Please, check.

**Comment by paladox** [comment]
Hi the patch is mainly for working with the timedmediahandler extension but I can have a look.

**Comment by paladox** [comment]
We also had the problem your seeing it seems it isent creating the data-res tag for the resolution our workaround was to use data-shorttitle since data-res wasent being created or wasent correctly finding the resolutions for those videos and displaying them in the list.

File: video-quality-selector.js [hunk 1]
```diff
@@ -381,7 +385,9 @@
 		});
 		
 		// Add the button to the control bar object and the DOM
-		player.controlBar.resolutionSelector = player.controlBar.addChild( resolutionSelector );
+		this.on( 'ready' , function() {
```
Comment (paladox) [inline video-quality-selector.js]: Maybe it could be this part. causing the problem for you.

**Comment by paladox** [comment]
It shows these errors

SCRIPT438: Object doesn't support property or method 'extends'

VIDEOJS: ERROR: Unable to find plugin: resolutionSelector

in the f12 developer tool in internet explorer.

File: video-quality-selector.js (hunk 1 above)
Comment (RomanEmelyanov) [inline video-quality-selector.js]: Update http://us2.ytapi.com/dev/50.php with patch above, but not worked :(

**Comment by RomanEmelyanov** [comment]
Google Chrome errors in console:
Uncaught TypeError: _V_.extends is not a function 
VIDEOJS: ERROR: Unable to find plugin: resolutionSelector

**Comment by RomanEmelyanov** [comment]
Use https://github.com/kmoskwiak/videojs-resolution-switcher instead
